server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/auth/**, /admin/**, /usuarios/**
        - id: habitacion-service
          uri: lb://habitacion-service
          predicates:
            - Path=/rooms/**, /room-types/**, /rates/**

# Configuración de Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # http://discovery-server:8761/eureka
    fetch-registry: true

jwt:
  secret: "586E3272357538782F413F4428472B4B6250655368566B597033733676397924"